// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("rescript/lib/js/belt_Array.js");

var arr = [
  2,
  3,
  4,
  5,
  5,
  6
];

Belt_Array.forEach(arr, (function (x) {
        console.log(x);
        
      }));

Belt_Array.forEach(arr, (function (x) {
        console.log(x);
        
      }));

exports.arr = arr;
/*  Not a pure module */
