// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, World!");

function add(a, b) {
  return a + b | 0;
}

function add5(param) {
  return 5 + param | 0;
}

var x = 5;

console.log(x);

function add9(param) {
  return 9 + param | 0;
}

var y = 17;

console.log(y);

exports.add = add;
exports.add5 = add5;
exports.x = x;
exports.add9 = add9;
exports.y = y;
/*  Not a pure module */
