// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Navbar from "../components/navbar/navbar.bs.js";

function Form(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setName = match[1];
  var handleInput = function ($$event) {
    var updatedName = $$event.target.value;
    return Curry._1(setName, (function (param) {
                  return updatedName;
                }));
  };
  return React.createElement(React.Fragment, undefined, React.createElement(Navbar.make, {}), React.createElement("h1", undefined, "Form Page"), React.createElement("div", undefined, match[0]), React.createElement("input", {
                  type: "text",
                  onChange: handleInput
                }));
}

var make = Form;

export {
  make ,
  
}
/* react Not a pure module */
