// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function FourOFour(Props) {
  return React.createElement("h1", undefined, "Page not found");
}

var make = FourOFour;

export {
  make ,
  
}
/* react Not a pure module */
