// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Navbar from "../components/navbar/navbar.bs.js";

function Index(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement(Navbar.make, {}), React.createElement("h1", undefined, "Home Page"));
}

var make = Index;

export {
  make ,
  
}
/* react Not a pure module */
