// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import NavModuleCss from "./Nav.module.css";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

var styles = NavModuleCss;

function Navbar(Props) {
  return React.createElement("div", {
              className: styles.wrapper
            }, React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("home");
                    })
                }, "Home"), React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("about");
                    })
                }, "About"), React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("form");
                    })
                }, "Form"), React.createElement("div", undefined), React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("counter");
                    })
                }, "Counter"), React.createElement("div", undefined), React.createElement("div", {
                  className: styles.link,
                  onClick: (function (param) {
                      return RescriptReactRouter.push("zoo");
                    })
                }, "Zoo"), React.createElement("div", undefined));
}

var make = Navbar;

export {
  styles ,
  make ,
  
}
/* styles Not a pure module */
