// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zoo from "./components/zoo/Zoo.bs.js";
import * as Form from "./pages/form.bs.js";
import * as About from "./pages/about.bs.js";
import * as Index from "./pages/index.bs.js";
import * as React from "react";
import * as Counter from "./components/counter/Counter.bs.js";
import * as FourOFour from "./pages/FourOFour.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match) {
    var exit = 0;
    switch (match.hd) {
      case "about" :
          if (!match.tl) {
            return React.createElement(About.make, {});
          }
          break;
      case "counter" :
          if (!match.tl) {
            return React.createElement(Counter.make, {});
          }
          break;
      case "form" :
          if (!match.tl) {
            return React.createElement(Form.make, {});
          }
          break;
      case "" :
      case "home" :
          exit = 2;
          break;
      case "zoo" :
          if (!match.tl) {
            return React.createElement(Zoo.make, {});
          }
          break;
      default:
        
    }
    if (exit === 2 && !match.tl) {
      return React.createElement(Index.make, {});
    }
    
  }
  return React.createElement(FourOFour.make, {});
}

var make = App;

export {
  make ,
  
}
/* Zoo Not a pure module */
