// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ZooHeader from "./ZooHeader.bs.js";

import './zoo.css'
;

var state = {
  selectedAnimal: undefined
};

function reducer(state, action) {
  return {
          selectedAnimal: action._0
        };
}

function animalString(x) {
  if (typeof x === "number") {
    return "Zebra";
  } else if (x.TAG === /* Giraffe */0) {
    return "Giraffe of height  " + String(x._0);
  } else {
    return "Dog is " + (
            x._0 ? "barking" : " not barking"
          );
  }
}

function getAnimalString(a) {
  if (a !== undefined) {
    return animalString(a);
  } else {
    return "No animal";
  }
}

function Zoo(Props) {
  var match = React.useReducer(reducer, state);
  var dispatch = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement("div", undefined, React.createElement(ZooHeader.make, {
                      description: getAnimalString(match[0].selectedAnimal)
                    }), React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* AnimalSelected */{
                                      _0: /* Zebra */0
                                    });
                        })
                    }, "Select Zebra"), React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* AnimalSelected */{
                                      _0: {
                                        TAG: /* Giraffe */0,
                                        _0: 2
                                      }
                                    });
                        })
                    }, "Select Giraffe"), React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(dispatch, /* AnimalSelected */{
                                      _0: {
                                        TAG: /* Dog */1,
                                        _0: true
                                      }
                                    });
                        })
                    }, "Select Dog")));
}

var make = Zoo;

export {
  state ,
  reducer ,
  animalString ,
  getAnimalString ,
  make ,
  
}
/*  Not a pure module */
