// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Navbar from "../navbar/navbar.bs.js";

function ZooHeader(Props) {
  var description = Props.description;
  return React.createElement(React.Fragment, undefined, React.createElement(Navbar.make, {}), React.createElement("h2", undefined, "Selected animal: " + description));
}

var make = ZooHeader;

export {
  make ,
  
}
/* react Not a pure module */
